升级 actions/upload-artifact

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -27,12 +27,17 @@ jobs:
       - name: Install Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          # 统一 Node.js 版本
+          node-version: 20.18
           cache: 'pnpm'
 
       - name: Install dependencies
-        run: pnpm install
-      - run: pnpm run build:h5
+        run: |
+          pnpm install || { echo "pnpm install failed"; exit 1; }
+
+      - run: |
+          pnpm run build:h5 || { echo "pnpm run build:h5 failed"; exit 1; }
+
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
